function_definitions = {
    'add_1': {
        'python_definition': 'lambda n: n + 1',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 1 to the input',
    },
    'add_14': {
        'python_definition': 'lambda n: n + 14',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 14 to the input',
    },
    'multiply_3': {
        'python_definition': 'lambda n: n * 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by 3',
    },
    'multiply_4': {
        'python_definition': 'lambda n: n * 4',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by 4',
    },
    'int_div_2': {
        'python_definition': 'lambda n: n // 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Integer division',
        'language_definition': 'Integer division by 2',
    },
    'int_div_3': {
        'python_definition': 'lambda n: n // 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Integer division',
        'language_definition': 'Integer division by 3',
    },
    'int_div_4': {
        'python_definition': 'lambda n: n // 4',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Integer division',
        'language_definition': 'Integer division by 4',
    },
    'add_2': {
        'python_definition': 'lambda n: n + 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 2 to the input',
    },
    'add_3': {
        'python_definition': 'lambda n: n + 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 3 to the input',
    },
    'add_5': {
        'python_definition': 'lambda n: n + 5',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 5 to the input',
    },
    'multiply_2': {
        'python_definition': 'lambda n: n * 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by 2',
    },
    'negate': {
        'python_definition': 'lambda n: -n',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Negates the input',
    },
    'identity': {
        'python_definition': 'lambda n: n',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Identity',
        'language_definition': 'Returns the input unchanged',
    },
    'subtract_1': {
        'python_definition': 'lambda n: n - 1',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 1 from the input',
    },
    'subtract_2': {
        'python_definition': 'lambda n: n - 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 2 from the input',
    },
    'subtract_3': {
        'python_definition': 'lambda n: n - 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 3 from the input',
    },
    'mod_2': {
        'python_definition': 'lambda n: n % 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 2',
    },
    'mod_3': {
        'python_definition': 'lambda n: n % 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 3',
    },
    'mod_27': {
        'python_definition': 'lambda n: n % 27',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 27',
    },
    'mod_7': {
        'python_definition': 'lambda n: n % 7',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 7',
    },
    'bool_mod_2': {
        'python_definition': 'lambda n: n % 2 == 0',
        'n_inputs': 1,
        'output_type': 'bool',
        'function_class': 'Modulo',
        'language_definition': 'Returns True if the input is even, False otherwise',
    },
    'bool_geq_neg13': {
        'python_definition': 'lambda n: n >= -13',
        'n_inputs': 1,
        'output_type': 'bool',
        'function_class': 'Comparison',
        'language_definition': 'Returns True if the input is greater than or equal to -13, False otherwise',
    },
    'bool_geq_3': {
        'python_definition': 'lambda n: n >= 3',
        'n_inputs': 1,
        'output_type': 'bool',
        'function_class': 'Comparison',
        'language_definition': 'Returns True if the input is greater than or equal to 3, False otherwise',
    },
    'float_mult_7_div_4': {
        'python_definition': 'lambda n: n * 7 / 4',
        'n_inputs': 1,
        'output_type': 'float',
        'function_class': 'Float multiplication',
        'language_definition': 'Multiplies the input by 7/4',
    },
    'float_mult_3_div_2': {
        'python_definition': 'lambda n: n * 3 / 2',
        'n_inputs': 1,
        'output_type': 'float',
        'function_class': 'Float multiplication',
        'language_definition': 'Multiplies the input by 3/2',
    },
    'affine_6x_9': {
        'python_definition': 'lambda n: 6 * n + 9',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 6 times the input plus 9',
    },
    'affine_neg3x_15': {
        'python_definition': 'lambda n: -3 * n + 15',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns -3 times the input plus 15',
    },
    'affine_12x_neg21': {
        'python_definition': 'lambda n: 12 * n - 21',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 12 times the input minus 21',
    },
    'affine_neg11x_13': {
        'python_definition': 'lambda n: -11 * n + 13',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns -11 times the input plus 13',
    },
    'affine_neg2x_5': {
        'python_definition': 'lambda n: -2 * n + 5',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns -2 times the input plus 5',
    },
    'affine_3x_2': {
        'python_definition': 'lambda n: 3 * n + 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 3 times the input plus 2',
    },
    'multiply_neg4': {
        'python_definition': 'lambda n: n * -4',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by -4',
    },
    'subtract_3': {
        'python_definition': 'lambda n: n - 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 3 from the input',
    },
    'add_6': {
        'python_definition': 'lambda n: n + 6',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 6 to the input',
    },
    'affine_neg5x_3': {
        'python_definition': 'lambda n: -5 * n + 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns -5 times the input plus 3',
    },
    'int_div_3_plus_2': {
        'python_definition': 'lambda n: n // 3 + 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Integer division',
        'language_definition': 'Integer division by 3 plus 2',
    },
    'mod_14': {
        'python_definition': 'lambda n: n % 14',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 14',
    },
    'affine_2x_neg3': {
        'python_definition': 'lambda n: 2 * n - 3',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 2 times the input minus 3',
    },
    'add_4': {
        'python_definition': 'lambda n: n + 4',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 4 to the input',
    },
    'affine_3x_6': {
        'python_definition': 'lambda n: 3 * n + 6',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 3 times the input plus 6',
    },
    'add_51': {
        'python_definition': 'lambda n: n + 51',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 51 to the input',
    },
    'add_16': {
        'python_definition': 'lambda n: n + 16',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 16 to the input',
    },
    'relu_neg2': {
        'python_definition': 'lambda n: max(n, -2)',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'ReLU',
        'language_definition': 'Returns the maximum of the input and -2',
    },
    'multiply_15': {
        'python_definition': 'lambda n: n * 15',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by 15',
    },
    'multiply_41': {
        'python_definition': 'lambda n: n * 41',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Multiplication',
        'language_definition': 'Multiplies the input by 41',
    },
    'subtract_37': {
        'python_definition': 'lambda n: n - 37',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 37 from the input',
    },
    'add_35': {
        'python_definition': 'lambda n: n + 35',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 35 to the input',
    },
    'add_95': {
        'python_definition': 'lambda n: n + 95',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 95 to the input',
    },
    'int_div_3_plus_4': {
        'python_definition': 'lambda n: n // 3 + 4',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Integer division',
        'language_definition': 'Integer division by 3 plus 4',
    },
    'subtract_11': {
        'python_definition': 'lambda n: n - 11',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 11 from the input',
    },
    'mod_5': {
        'python_definition': 'lambda n: n % 5',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Modulo',
        'language_definition': 'Returns the input modulo 5',
    },
    'affine_3x_neg5': {
        'python_definition': 'lambda n: 3 * n - 5',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Affine linear',
        'language_definition': 'Returns 3 times the input minus 5',
    },
    'subtract_851': {
        'python_definition': 'lambda n: n - 851',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 851 from the input'
    },
    'add_44': {
        'python_definition': 'lambda n: n + 44',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 44 to the input'
    },
    'add_338': {
        'python_definition': 'lambda n: n + 338',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 338 to the input'
    },
    'subtract_551': {
        'python_definition': 'lambda n: n - 551',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 551 from the input'
    },
    'subtract_10': {
        'python_definition': 'lambda n: n - 10',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 10 from the input'
    },
    'subtract_265': {
        'python_definition': 'lambda n: n - 265',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 265 from the input'
    },
    'subtract_279': {
        'python_definition': 'lambda n: n - 279',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 279 from the input'
    },
    'subtract_512': {
        'python_definition': 'lambda n: n - 512',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 512 from the input'
    },
    'add_486': {
        'python_definition': 'lambda n: n + 486',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 486 to the input'
    },
    'subtract_513': {
        'python_definition': 'lambda n: n - 513',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 513 from the input'
    },
    'subtract_146': {
        'python_definition': 'lambda n: n - 146',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 146 from the input'
    },
    'subtract_72': {
        'python_definition': 'lambda n: n - 72',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 72 from the input'
    },
    'add_102': {
        'python_definition': 'lambda n: n + 102',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 102 to the input'
    },
    'add_195': {
        'python_definition': 'lambda n: n + 195',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 195 to the input'
    },
    'add_12': {
        'python_definition': 'lambda n: n + 12',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 12 to the input'
    },
    'subtract_16': {
        'python_definition': 'lambda n: n - 16',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 16 from the input'
    },
    'add_58': {
        'python_definition': 'lambda n: n + 58',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 58 to the input'
    },
    'add_152': {
        'python_definition': 'lambda n: n + 152',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 152 to the input'
    },
    'add_91': {
        'python_definition': 'lambda n: n + 91',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 91 to the input'
    },
    'add_883': {
        'python_definition': 'lambda n: n + 883',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 883 to the input'
    },
    'subtract_486': {
        'python_definition': 'lambda n: n - 486',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 486 from the input'
    },
    'add_296': {
        'python_definition': 'lambda n: n + 296',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Addition',
        'language_definition': 'Adds 296 to the input'
    },
    'subtract_108': {
        'python_definition': 'lambda n: n - 108',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Subtraction',
        'language_definition': 'Subtracts 108 from the input'
    },
    'piecewise_1': {
        'python_definition': 'lambda n: n * 3 if n < 0 else n * 2',
        'n_inputs': 1,
        'output_type': 'int',
        'function_class': 'Piecewise linear',
        'language_definition': 'Returns 3 times the input if it is negative, 2 times the input otherwise',
    },
}
